server:
  port: 8080

spring:
  application:
    name: ccpl-nisum-users
  datasource:
    url: jdbc:h2:mem:nisum
    username: nisum-user
    password: CCPLNisum2023
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  kafka:
    bootstrap-servers: http://localhost:9092
    producer:
      topic-name: nisum-kafka-topic
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      topic-name: nisum-kafka-topic
      group-id: nisum-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.nisum.ccplnisumusersapi.model.kafka

custom:
  password-regex: '^(?=.*[A-Z])(?=.*[a-z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$'

jwt:
  expiration:
    minutes: 1